#pragma once

enum COMP_TYPE { OP_ACCEPT, OP_RECV, OP_SEND, OP_NPC_MOVE, OP_AI_HELLO };
enum EVENT_TYPE { EV_RANDOM_MOVE };
enum SESSION_STATE { ST_FREE, ST_ALLOC, ST_INGAME };
enum MAP_INFO { MI_FREE, MI_CRACK_WALL, MI_SOILD_WALL, MI_ITEM };
